import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const avatorImage = 'https://static.wixstatic.com/media/5c0c47_8822633a37fe4fb5bc6e9c90c6a7acc4~mv2.jpeg/v1/fill/w_560,h_424,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/thewinning.jpeg'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routes = [
  { 
    link: '/',
    name: '首頁'
  },
  { 
    link: '/wiki',
    name: 'wiki'
  },
  { 
    link: '/pictures',
    name: '美照'
  },
  { 
    link: '/quote',
    name: '名言'
  },
  { 
    link: '/videos',
    name: '影片'
  },
  { 
    link: '/meme',
    name: '迷因'
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container">
          <div className="header">
            <div className="avator-block">
              <div className="avator-image">
                <img src={avatorImage} alt="23" title="avator" />
              </div>
              <div className="avator-context">
                {"This is Uaena's Page."}
              </div>
            </div>
            <div className="context"></div>
          </div>
          <div className="navbar">
            <ul>
              {routes.map(route => {
                const { link, name } = route;
                return (
                  <li>
                    <a href={link}>{name}</a>
                  </li>
                )
              })}
            </ul>
          </div>
          <div className="main-content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
